
package src.main.java.com.keysoft.soap.generated;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://soap.keysoft.com.java.main.src/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://soap.keysoft.com.java.main.src/", className = "src.main.java.com.keysoft.soap.generated.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://soap.keysoft.com.java.main.src/", className = "src.main.java.com.keysoft.soap.generated.GetAllResponse")
    public String getAll();

}
